-- MySQL Script generated by MySQL Workbench
-- Fri Apr  7 14:42:23 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Pausanias_INC
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Pausanias_INC
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Pausanias_INC` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
USE `Pausanias_INC` ;

-- -----------------------------------------------------
-- Table `Pausanias_INC`.`Worker`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pausanias_INC`.`Worker` (
  `Worker_ID` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Surname` VARCHAR(45) NOT NULL,
  `Address` VARCHAR(45) NOT NULL,
  `SSN` INT NOT NULL,
  `Wage` FLOAT NOT NULL,
  `Branch_ID` INT NOT NULL,
  `Started_Working` DATE NOT NULL,
  `Fired_on` DATE NULL,
  PRIMARY KEY (`Worker_ID`),
  INDEX `fk_Worker_branch1_idx` (`Branch_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Worker_branch1`
    FOREIGN KEY (`Branch_ID`)
    REFERENCES `Pausanias_INC`.`Branch` (`Branch_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pausanias_INC`.`Admin_Worker`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pausanias_INC`.`Admin_Worker` (
  `Worker_ID` INT NOT NULL,
  `Degree` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Worker_ID`),
  CONSTRAINT `fk_Admin_Worker_Worker1`
    FOREIGN KEY (`Worker_ID`)
    REFERENCES `Pausanias_INC`.`Worker` (`Worker_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pausanias_INC`.`IT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pausanias_INC`.`IT` (
  `Worker_ID` INT NOT NULL,
  `CV` LONGTEXT NOT NULL,
  PRIMARY KEY (`Worker_ID`),
  CONSTRAINT `fk_IT_Admin_Worker1`
    FOREIGN KEY (`Worker_ID`)
    REFERENCES `Pausanias_INC`.`Admin_Worker` (`Worker_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pausanias_INC`.`Branch`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pausanias_INC`.`Branch` (
  `Branch_ID` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Adress` VARCHAR(45) NOT NULL,
  `Master_Password` VARCHAR(45) NOT NULL,
  `IT_Master_ID` INT NOT NULL,
  `Manager_ID` INT NOT NULL,
  PRIMARY KEY (`Branch_ID`),
  INDEX `fk_Branch_IT1_idx` (`IT_Master_ID` ASC) VISIBLE,
  INDEX `fk_Branch_Admin_Worker1_idx` (`Manager_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Branch_IT1`
    FOREIGN KEY (`IT_Master_ID`)
    REFERENCES `Pausanias_INC`.`IT` (`Worker_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Branch_Admin_Worker1`
    FOREIGN KEY (`Manager_ID`)
    REFERENCES `Pausanias_INC`.`Admin_Worker` (`Worker_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pausanias_INC`.`Telephone Numbers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pausanias_INC`.`Telephone Numbers` (
  `Number` INT NOT NULL,
  `Branch_ID` INT NOT NULL,
  PRIMARY KEY (`Number`),
  INDEX `fk_Telephone Numbers_branch_idx` (`Branch_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Telephone Numbers_branch`
    FOREIGN KEY (`Branch_ID`)
    REFERENCES `Pausanias_INC`.`Branch` (`Branch_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pausanias_INC`.`Accountant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pausanias_INC`.`Accountant` (
  `Worker_ID` INT NOT NULL,
  PRIMARY KEY (`Worker_ID`),
  CONSTRAINT `fk_Accountant_Admin_Worker1`
    FOREIGN KEY (`Worker_ID`)
    REFERENCES `Pausanias_INC`.`Admin_Worker` (`Worker_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pausanias_INC`.`Driver`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pausanias_INC`.`Driver` (
  `Worker_ID` INT NOT NULL,
  `Licence` VARCHAR(45) NOT NULL,
  `Experience` INT NOT NULL,
  `Range` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Worker_ID`),
  INDEX `fk_Driver_Worker1_idx` (`Worker_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Driver_Worker1`
    FOREIGN KEY (`Worker_ID`)
    REFERENCES `Pausanias_INC`.`Worker` (`Worker_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pausanias_INC`.`Guide`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pausanias_INC`.`Guide` (
  `Worker_ID` INT NOT NULL,
  `CV` LONGTEXT NOT NULL,
  PRIMARY KEY (`Worker_ID`),
  INDEX `fk_Guide_Worker1_idx` (`Worker_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Guide_Worker1`
    FOREIGN KEY (`Worker_ID`)
    REFERENCES `Pausanias_INC`.`Worker` (`Worker_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pausanias_INC`.`Logistic`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pausanias_INC`.`Logistic` (
  `Worker_ID` INT NOT NULL,
  PRIMARY KEY (`Worker_ID`),
  CONSTRAINT `fk_Logistic_Admin_Worker1`
    FOREIGN KEY (`Worker_ID`)
    REFERENCES `Pausanias_INC`.`Admin_Worker` (`Worker_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pausanias_INC`.`Admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pausanias_INC`.`Admin` (
  `Worker_ID` INT NOT NULL,
  PRIMARY KEY (`Worker_ID`),
  CONSTRAINT `fk_Admin_Admin_Worker1`
    FOREIGN KEY (`Worker_ID`)
    REFERENCES `Pausanias_INC`.`Admin_Worker` (`Worker_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pausanias_INC`.`Language`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pausanias_INC`.`Language` (
  `Language` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Language`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pausanias_INC`.`Place`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pausanias_INC`.`Place` (
  `Name` VARCHAR(45) NOT NULL,
  `Country` VARCHAR(45) NOT NULL,
  `Description` LONGTEXT NOT NULL,
  `Language` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Name`, `Country`),
  INDEX `fk_Place_Language1_idx` (`Language` ASC) VISIBLE,
  CONSTRAINT `fk_Place_Language1`
    FOREIGN KEY (`Language`)
    REFERENCES `Pausanias_INC`.`Language` (`Language`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pausanias_INC`.`Destination`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pausanias_INC`.`Destination` (
  `Destination_ID` INT NOT NULL,
  `Distance` FLOAT NOT NULL,
  `Next_Destination_ID` INT NULL,
  `Place_Name` VARCHAR(45) NOT NULL,
  `Place_Country` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Destination_ID`, `Place_Name`, `Place_Country`),
  INDEX `fk_Destination_Destination1_idx` (`Next_Destination_ID` ASC) VISIBLE,
  INDEX `fk_Destination_Place1_idx` (`Place_Name` ASC, `Place_Country` ASC) VISIBLE,
  CONSTRAINT `fk_Destination_Destination1`
    FOREIGN KEY (`Next_Destination_ID`)
    REFERENCES `Pausanias_INC`.`Destination` (`Destination_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Destination_Place1`
    FOREIGN KEY (`Place_Name` , `Place_Country`)
    REFERENCES `Pausanias_INC`.`Place` (`Name` , `Country`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pausanias_INC`.`Trip`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pausanias_INC`.`Trip` (
  `Trip_ID` INT NOT NULL,
  `Departure_Date` DATE NOT NULL,
  `Return_Date` DATE NOT NULL,
  `Num_of_Travellers` INT NOT NULL,
  `Cost_Per_Traveller` FLOAT NOT NULL,
  `Destination_ID` INT NOT NULL,
  PRIMARY KEY (`Trip_ID`),
  INDEX `fk_Trip_Destination1_idx` (`Destination_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Trip_Destination1`
    FOREIGN KEY (`Destination_ID`)
    REFERENCES `Pausanias_INC`.`Destination` (`Destination_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pausanias_INC`.`Sight`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pausanias_INC`.`Sight` (
  `Sight_ID` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Type` VARCHAR(45) NOT NULL,
  `Place_Name` VARCHAR(45) NOT NULL,
  `Place_Country` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Sight_ID`),
  INDEX `fk_Sight_Place1_idx` (`Place_Name` ASC, `Place_Country` ASC) VISIBLE,
  CONSTRAINT `fk_Sight_Place1`
    FOREIGN KEY (`Place_Name` , `Place_Country`)
    REFERENCES `Pausanias_INC`.`Place` (`Name` , `Country`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pausanias_INC`.`Other_Venues`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pausanias_INC`.`Other_Venues` (
  `Venue_ID` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Type` VARCHAR(45) NOT NULL,
  `Place_Name` VARCHAR(45) NOT NULL,
  `Place_Country` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Venue_ID`),
  INDEX `fk_Other_Venues_Place1_idx` (`Place_Name` ASC, `Place_Country` ASC) VISIBLE,
  CONSTRAINT `fk_Other_Venues_Place1`
    FOREIGN KEY (`Place_Name` , `Place_Country`)
    REFERENCES `Pausanias_INC`.`Place` (`Name` , `Country`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pausanias_INC`.`Tour`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pausanias_INC`.`Tour` (
  `Guide_Worker_ID` INT NOT NULL,
  `Trip_ID` INT NOT NULL,
  `Sight_ID` INT NOT NULL,
  PRIMARY KEY (`Guide_Worker_ID`, `Trip_ID`, `Sight_ID`),
  INDEX `fk_Tour_Trip1_idx` (`Trip_ID` ASC) VISIBLE,
  INDEX `fk_Tour_Sight1_idx` (`Sight_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Tour_Guide1`
    FOREIGN KEY (`Guide_Worker_ID`)
    REFERENCES `Pausanias_INC`.`Guide` (`Worker_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Tour_Trip1`
    FOREIGN KEY (`Trip_ID`)
    REFERENCES `Pausanias_INC`.`Trip` (`Trip_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Tour_Sight1`
    FOREIGN KEY (`Sight_ID`)
    REFERENCES `Pausanias_INC`.`Sight` (`Sight_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pausanias_INC`.`Offer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pausanias_INC`.`Offer` (
  `Offer_ID` INT NOT NULL,
  `Starting_Date` DATE NOT NULL,
  `Ending_Date` DATE NOT NULL,
  `Cost` FLOAT NOT NULL,
  `Type` VARCHAR(45) NOT NULL,
  `Description` VARCHAR(45) NOT NULL,
  `Trip_ID` INT NOT NULL,
  PRIMARY KEY (`Offer_ID`),
  INDEX `fk_Offer_Trip1_idx` (`Trip_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Offer_Trip1`
    FOREIGN KEY (`Trip_ID`)
    REFERENCES `Pausanias_INC`.`Trip` (`Trip_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pausanias_INC`.`Traveler`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pausanias_INC`.`Traveler` (
  `Traveler_ID` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Surname` VARCHAR(45) NOT NULL,
  `Address` VARCHAR(45) NOT NULL,
  `Age` INT NOT NULL,
  `Telephone` INT NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `Type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Traveler_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pausanias_INC`.`Booking`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pausanias_INC`.`Booking` (
  `Booking_ID` INT NOT NULL,
  `Date` VARCHAR(45) NOT NULL,
  `Upfront_Payment` FLOAT NOT NULL,
  `Offer_ID` INT NOT NULL,
  `Branch_ID` INT NOT NULL,
  `Traveler_ID` INT NOT NULL,
  PRIMARY KEY (`Booking_ID`),
  INDEX `fk_Booking_Offer1_idx` (`Offer_ID` ASC) VISIBLE,
  INDEX `fk_Booking_Branch1_idx` (`Branch_ID` ASC) VISIBLE,
  INDEX `fk_Booking_Traveler1_idx` (`Traveler_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Booking_Offer1`
    FOREIGN KEY (`Offer_ID`)
    REFERENCES `Pausanias_INC`.`Offer` (`Offer_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Booking_Branch1`
    FOREIGN KEY (`Branch_ID`)
    REFERENCES `Pausanias_INC`.`Branch` (`Branch_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Booking_Traveler1`
    FOREIGN KEY (`Traveler_ID`)
    REFERENCES `Pausanias_INC`.`Traveler` (`Traveler_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pausanias_INC`.`Guide_Knows_Language`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pausanias_INC`.`Guide_Knows_Language` (
  `Guide_Worker_ID` INT NOT NULL,
  `Language` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Guide_Worker_ID`, `Language`),
  INDEX `fk_Guide_has_Language_Language1_idx` (`Language` ASC) VISIBLE,
  INDEX `fk_Guide_has_Language_Guide1_idx` (`Guide_Worker_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Guide_has_Language_Guide1`
    FOREIGN KEY (`Guide_Worker_ID`)
    REFERENCES `Pausanias_INC`.`Guide` (`Worker_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Guide_has_Language_Language1`
    FOREIGN KEY (`Language`)
    REFERENCES `Pausanias_INC`.`Language` (`Language`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pausanias_INC`.`Trip_has_Happening_at`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pausanias_INC`.`Trip_has_Happening_at` (
  `Trip_ID` INT NOT NULL,
  `Other_Venues_ID` INT NOT NULL,
  PRIMARY KEY (`Trip_ID`, `Other_Venues_ID`),
  INDEX `fk_Trip_has_Other_Venues_Other_Venues1_idx` (`Other_Venues_ID` ASC) VISIBLE,
  INDEX `fk_Trip_has_Other_Venues_Trip1_idx` (`Trip_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Trip_has_Other_Venues_Trip1`
    FOREIGN KEY (`Trip_ID`)
    REFERENCES `Pausanias_INC`.`Trip` (`Trip_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Trip_has_Other_Venues_Other_Venues1`
    FOREIGN KEY (`Other_Venues_ID`)
    REFERENCES `Pausanias_INC`.`Other_Venues` (`Venue_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
